ALTER TABLE hooptie
RENAME TO car_table,
ADD COLUMN car_id INT NOT NULL AUTO_INCREMENT FIRST,
ADD PRIMARY KEY (car_id),
ADD COLUMN VIN VARCHAR(16) AFTER car id,
CHANGE COLUMN mo model VARCHAR(20),
MODIFY COLUMN color VARCHAR(6) AFTER model,
MODIFY COLUMN year VARCHAR(4) SIXTH,
CHANGE COLUMN howmuch price DECIMAL(7,2);